# Generated by Django 2.2 on 2019-10-23 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='deadline')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('solution', models.FileField(upload_to='question/files/')),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauth.RegUser')),
            ],
        ),
    ]
