# Generated by Django 2.2 on 2019-10-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_studentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
