# Generated by Django 2.2 on 2019-10-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20191023_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
