# Generated by Django 2.2 on 2019-11-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20191023_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='fingerprints',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='kgrams',
            field=models.TextField(null=True),
        ),
    ]
